spring:
  application:
    name: qrcode-service
  config:
    import: "consul:"
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        healthCheckPath: /api/v1/service-health-check
        healthCheckInterval: 20s
  kafka:
    consumer:
      group-id: diploma-id
server:
  port: 8083
